const data = [{
  id: 168456970,
  node_id: 'MDEwOlJlcG9zaXRvcnkxNjg0NTY5NzA=',
  name: 'e-store',
  full_name: 'evo-g/e-store',
  private: false,
  owner: {
    login: 'evo-g',
    id: 35902060,
    node_id: 'MDQ6VXNlcjM1OTAyMDYw',
    avatar_url: 'https://avatars0.githubusercontent.com/u/35902060?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/evo-g',
    html_url: 'https://github.com/evo-g',
    followers_url: 'https://api.github.com/users/evo-g/followers',
    following_url: 'https://api.github.com/users/evo-g/following{/other_user}',
    gists_url: 'https://api.github.com/users/evo-g/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/evo-g/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/evo-g/subscriptions',
    organizations_url: 'https://api.github.com/users/evo-g/orgs',
    repos_url: 'https://api.github.com/users/evo-g/repos',
    events_url: 'https://api.github.com/users/evo-g/events{/privacy}',
    received_events_url: 'https://api.github.com/users/evo-g/received_events',
    type: 'User',
    site_admin: false
  },
  html_url: 'https://github.com/evo-g/e-store',
  description: 'e-commerce store tutorial ',
  fork: false,
  url: 'https://api.github.com/repos/evo-g/e-store',
  forks_url: 'https://api.github.com/repos/evo-g/e-store/forks',
  keys_url: 'https://api.github.com/repos/evo-g/e-store/keys{/key_id}',
  collaborators_url: 'https://api.github.com/repos/evo-g/e-store/collaborators{/collaborator}',
  teams_url: 'https://api.github.com/repos/evo-g/e-store/teams',
  hooks_url: 'https://api.github.com/repos/evo-g/e-store/hooks',
  issue_events_url: 'https://api.github.com/repos/evo-g/e-store/issues/events{/number}',
  events_url: 'https://api.github.com/repos/evo-g/e-store/events',
  assignees_url: 'https://api.github.com/repos/evo-g/e-store/assignees{/user}',
  branches_url: 'https://api.github.com/repos/evo-g/e-store/branches{/branch}',
  tags_url: 'https://api.github.com/repos/evo-g/e-store/tags',
  blobs_url: 'https://api.github.com/repos/evo-g/e-store/git/blobs{/sha}',
  git_tags_url: 'https://api.github.com/repos/evo-g/e-store/git/tags{/sha}',
  git_refs_url: 'https://api.github.com/repos/evo-g/e-store/git/refs{/sha}',
  trees_url: 'https://api.github.com/repos/evo-g/e-store/git/trees{/sha}',
  statuses_url: 'https://api.github.com/repos/evo-g/e-store/statuses/{sha}',
  languages_url: 'https://api.github.com/repos/evo-g/e-store/languages',
  stargazers_url: 'https://api.github.com/repos/evo-g/e-store/stargazers',
  contributors_url: 'https://api.github.com/repos/evo-g/e-store/contributors',
  subscribers_url: 'https://api.github.com/repos/evo-g/e-store/subscribers',
  subscription_url: 'https://api.github.com/repos/evo-g/e-store/subscription',
  commits_url: 'https://api.github.com/repos/evo-g/e-store/commits{/sha}',
  git_commits_url: 'https://api.github.com/repos/evo-g/e-store/git/commits{/sha}',
  comments_url: 'https://api.github.com/repos/evo-g/e-store/comments{/number}',
  issue_comment_url: 'https://api.github.com/repos/evo-g/e-store/issues/comments{/number}',
  contents_url: 'https://api.github.com/repos/evo-g/e-store/contents/{+path}',
  compare_url: 'https://api.github.com/repos/evo-g/e-store/compare/{base}...{head}',
  merges_url: 'https://api.github.com/repos/evo-g/e-store/merges',
  archive_url: 'https://api.github.com/repos/evo-g/e-store/{archive_format}{/ref}',
  downloads_url: 'https://api.github.com/repos/evo-g/e-store/downloads',
  issues_url: 'https://api.github.com/repos/evo-g/e-store/issues{/number}',
  pulls_url: 'https://api.github.com/repos/evo-g/e-store/pulls{/number}',
  milestones_url: 'https://api.github.com/repos/evo-g/e-store/milestones{/number}',
  notifications_url: 'https://api.github.com/repos/evo-g/e-store/notifications{?since,all,participating}',
  labels_url: 'https://api.github.com/repos/evo-g/e-store/labels{/name}',
  releases_url: 'https://api.github.com/repos/evo-g/e-store/releases{/id}',
  deployments_url: 'https://api.github.com/repos/evo-g/e-store/deployments',
  created_at: '2019-01-31T03:33:21Z',
  updated_at: '2019-04-28T04:09:11Z',
  pushed_at: '2019-04-12T22:23:05Z',
  git_url: 'git://github.com/evo-g/e-store.git',
  ssh_url: 'git@github.com:evo-g/e-store.git',
  clone_url: 'https://github.com/evo-g/e-store.git',
  svn_url: 'https://github.com/evo-g/e-store',
  homepage: null,
  size: 474,
  stargazers_count: 1,
  watchers_count: 1,
  language: 'JavaScript',
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: false,
  forks_count: 0,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 0,
  license: null,
  forks: 0,
  open_issues: 0,
  watchers: 1,
  default_branch: 'master'
}];

const getIssues = data => data.map(
  ({ name, description, issues_url, open_issues, open_issues_count, html_url }) =>
    ({ name, description, issues_url, open_issues, open_issues_count, html_url })
);

const output = getIssues(data);

const expected = [{
  name: 'e-store',
  description: 'e-commerce store tutorial ',
  issues_url: 'https://api.github.com/repos/evo-g/e-store/issues{/number}',
  open_issues_count: 0,
  html_url: 'https://github.com/evo-g/e-store',
}];

console.log(output, expected);
